package com.baka4n.elementera.api.reg;

import com.baka4n.elementera.api.items.*;
import net.minecraft.item.Item;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

import static com.baka4n.elementera.api.Psf.MOD_ID;

public class RegItem {
    public static final DeferredRegister<Item> ITEMS = new DeferredRegister<>(ForgeRegistries.ITEMS, MOD_ID);
    public static final RegistryObject<Item> PROTIUM = ITEMS.register("protium", Protium::new);
    public static final RegistryObject<Item> DEUTERIUM = ITEMS.register("deuterium", Deuterium::new);
    public static final RegistryObject<Item> TRITIUM = ITEMS.register("tritium", Tritium::new);
    public static final RegistryObject<Item> HELIUM_2 = ITEMS.register("helium_2", Helium::new);
    public static final RegistryObject<Item> HELIUM_3 = ITEMS.register("helium_3", Helium::new);
    public static final RegistryObject<Item> HELIUM = ITEMS.register("helium", Helium::new);
    public static final RegistryObject<Item> HELIUM_5 = ITEMS.register("helium_5", Helium::new);
    public static final RegistryObject<Item> HELIUM_6 = ITEMS.register("helium_6", Helium::new);
    public static final RegistryObject<Item> HELIUM_7 = ITEMS.register("helium_7", Helium::new);
    public static final RegistryObject<Item> HELIUM_8 = ITEMS.register("helium_8", Helium::new);
    public static final RegistryObject<Item> HELIUM_9 = ITEMS.register("helium_9", Helium::new);
    public static final RegistryObject<Item> HELIUM_10 = ITEMS.register("helium_10", Helium::new);
    public static final RegistryObject<Item> LITHIUM_6 = ITEMS.register("lithium_6", Lithium::new);
    public static final RegistryObject<Item> LITHIUM = ITEMS.register("lithium", Lithium::new);
    public static final RegistryObject<Item> BERYLLIUM_7 = ITEMS.register("beryllium_7", Beryllium::new);
    public static final RegistryObject<Item> BERYLLIUM = ITEMS.register("beryllium", Beryllium::new);
    public static final RegistryObject<Item> BERYLLIUM_9 = ITEMS.register("beryllium_9", Beryllium::new);
    public static final RegistryObject<Item> BERYLLIUM_10 = ITEMS.register("beryllium_10", Beryllium::new);
    public static final RegistryObject<Item> BORON_6 = ITEMS.register("boron_6", Boron::new);
    public static final RegistryObject<Item> BORON_7 = ITEMS.register("boron_7", Boron::new);
    public static final RegistryObject<Item> BORON_8 = ITEMS.register("boron_8", Boron::new);
    public static final RegistryObject<Item> BORON_9 = ITEMS.register("boron_9", Boron::new);
    public static final RegistryObject<Item> BORON_10 = ITEMS.register("boron_10", Boron::new);
    public static final RegistryObject<Item> BORON_11 = ITEMS.register("boron_11", Boron::new);
    public static final RegistryObject<Item> BORON_12 = ITEMS.register("boron_12", Boron::new);
    public static final RegistryObject<Item> BORON_13 = ITEMS.register("boron_13", Boron::new);
    public static final RegistryObject<Item> BORON_14 = ITEMS.register("boron_14", Boron::new);
    public static final RegistryObject<Item> BORON_15 = ITEMS.register("boron_15", Boron::new);
    public static final RegistryObject<Item> BORON_16 = ITEMS.register("boron_16", Boron::new);
    public static final RegistryObject<Item> BORON_17 = ITEMS.register("boron_17", Boron::new);
    public static final RegistryObject<Item> BORON_18 = ITEMS.register("boron_18", Boron::new);
    public static final RegistryObject<Item> BORON_19 = ITEMS.register("boron_19", Boron::new);
    public static final RegistryObject<Item> CARBON_8 = ITEMS.register("carbon_8", Carbon::new);
    public static final RegistryObject<Item> CARBON_9 = ITEMS.register("carbon_9", Carbon::new);
    public static final RegistryObject<Item> CARBON_10 = ITEMS.register("carbon_10", Carbon::new);
    public static final RegistryObject<Item> CARBON_11 = ITEMS.register("carbon_11", Carbon::new);
    public static final RegistryObject<Item> CARBON_12 = ITEMS.register("carbon_12", Carbon::new);
    public static final RegistryObject<Item> CARBON_13 = ITEMS.register("carbon_13", Carbon::new);
    public static final RegistryObject<Item> CARBON_14 = ITEMS.register("carbon_14", Carbon::new);
    public static final RegistryObject<Item> CARBON_15 = ITEMS.register("carbon_15", Carbon::new);
    public static final RegistryObject<Item> CARBON_16 = ITEMS.register("carbon_16", Carbon::new);
    public static final RegistryObject<Item> CARBON_17 = ITEMS.register("carbon_17", Carbon::new);
    public static final RegistryObject<Item> CARBON_18 = ITEMS.register("carbon_18", Carbon::new);
    public static final RegistryObject<Item> CARBON_19 = ITEMS.register("carbon_19", Carbon::new);
    public static final RegistryObject<Item> CARBON_20 = ITEMS.register("carbon_20", Carbon::new);
    public static final RegistryObject<Item> CARBON_21 = ITEMS.register("carbon_21", Carbon::new);
    public static final RegistryObject<Item> CARBON_22 = ITEMS.register("carbon_22", Carbon::new);
    public static final RegistryObject<Item> NITROGEN_10 = ITEMS.register("nitrogen_10", Nitrogen::new);
    public static final RegistryObject<Item> NITROGEN_11 = ITEMS.register("nitrogen_11", Nitrogen::new);
    public static final RegistryObject<Item> NITROGEN_12 = ITEMS.register("nitrogen_12", Nitrogen::new);
    public static final RegistryObject<Item> NITROGEN_13 = ITEMS.register("nitrogen_13", Nitrogen::new);
    public static final RegistryObject<Item> NITROGEN = ITEMS.register("nitrogen", Nitrogen::new);
    public static final RegistryObject<Item> NITROGEN_15 = ITEMS.register("nitrogen_15", Nitrogen::new);
    public static final RegistryObject<Item> NITROGEN_16 = ITEMS.register("nitrogen_16", Nitrogen::new);
    public static final RegistryObject<Item> NITROGEN_17 = ITEMS.register("nitrogen_17", Nitrogen::new);
    public static final RegistryObject<Item> NITROGEN_18 = ITEMS.register("nitrogen_18", Nitrogen::new);
    public static final RegistryObject<Item> NITROGEN_19 = ITEMS.register("nitrogen_19", Nitrogen::new);
    public static final RegistryObject<Item> NITROGEN_20= ITEMS.register("nitrogen_20", Nitrogen::new);
    public static final RegistryObject<Item> NITROGEN_21 = ITEMS.register("nitrogen_21", Nitrogen::new);
    public static final RegistryObject<Item> NITROGEN_22 = ITEMS.register("nitrogen_22", Nitrogen::new);
    public static final RegistryObject<Item> NITROGEN_23 = ITEMS.register("nitrogen_23", Nitrogen::new);
    public static final RegistryObject<Item> NITROGEN_24 = ITEMS.register("nitrogen_24", Nitrogen::new);
    public static final RegistryObject<Item> NITROGEN_25 = ITEMS.register("nitrogen_25", Nitrogen::new);
    public static final RegistryObject<Item> OXYGEN_13 = ITEMS.register("oxygen_13", Oxygen::new);
    public static final RegistryObject<Item> OXYGEN_14 = ITEMS.register("oxygen_14", Oxygen::new);
    public static final RegistryObject<Item> OXYGEN_15 = ITEMS.register("oxygen_15", Oxygen::new);
    public static final RegistryObject<Item> OXYGEN = ITEMS.register("oxygen", Oxygen::new);
    public static final RegistryObject<Item> OXYGEN_17 = ITEMS.register("oxygen_17", Oxygen::new);
    public static final RegistryObject<Item> OXYGEN_18 = ITEMS.register("oxygen_18", Oxygen::new);
    public static final RegistryObject<Item> OXYGEN_19 = ITEMS.register("oxygen_19", Oxygen::new);
    public static final RegistryObject<Item> OXYGEN_20 = ITEMS.register("oxygen_20", Oxygen::new);
    public static final RegistryObject<Item> OXYGEN_21 = ITEMS.register("oxygen_21", Oxygen::new);
    public static final RegistryObject<Item> OXYGEN_22 = ITEMS.register("oxygen_22", Oxygen::new);
    public static final RegistryObject<Item> OXYGEN_23 = ITEMS.register("oxygen_23", Oxygen::new);
    public static final RegistryObject<Item> OXYGEN_24 = ITEMS.register("oxygen_24", Oxygen::new);
    public static final RegistryObject<Item> FLUORINE_14 = ITEMS.register("fluorine_14", Fluorine::new);
    public static final RegistryObject<Item> FLUORINE_15 = ITEMS.register("fluorine_15", Fluorine::new);
    public static final RegistryObject<Item> FLUORINE_16 = ITEMS.register("fluorine_16", Fluorine::new);
    public static final RegistryObject<Item> FLUORINE_17 = ITEMS.register("fluorine_17", Fluorine::new);
    public static final RegistryObject<Item> FLUORINE_18 = ITEMS.register("fluorine_18", Fluorine::new);
    public static final RegistryObject<Item> FLUORINE = ITEMS.register("fluorine", Fluorine::new);
    public static final RegistryObject<Item> FLUORINE_20 = ITEMS.register("fluorine_20", Fluorine::new);
    public static final RegistryObject<Item> FLUORINE_21 = ITEMS.register("fluorine_21", Fluorine::new);
    public static final RegistryObject<Item> FLUORINE_22 = ITEMS.register("fluorine_22", Fluorine::new);
    public static final RegistryObject<Item> FLUORINE_23 = ITEMS.register("fluorine_23", Fluorine::new);
    public static final RegistryObject<Item> FLUORINE_24 = ITEMS.register("fluorine_24", Fluorine::new);
    public static final RegistryObject<Item> FLUORINE_25 = ITEMS.register("fluorine_25", Fluorine::new);
    public static final RegistryObject<Item> FLUORINE_26 = ITEMS.register("fluorine_26", Fluorine::new);
    public static final RegistryObject<Item> FLUORINE_27 = ITEMS.register("fluorine_27", Fluorine::new);
    public static final RegistryObject<Item> FLUORINE_28 = ITEMS.register("fluorine_28", Fluorine::new);
    public static final RegistryObject<Item> FLUORINE_29 = ITEMS.register("fluorine_29", Fluorine::new);
    public static final RegistryObject<Item> FLUORINE_30 = ITEMS.register("fluorine_30", Fluorine::new);
    public static final RegistryObject<Item> FLUORINE_31 = ITEMS.register("fluorine_31", Fluorine::new);

}
